### ISSUE TITLE
GAS stuck on doGet(e) -> 'Opening a row...'

### ISSUE THREAD

**Issue by cklann1** [mhawksey/OpenRow#1]
Thanks for the Gist, Martin.  
I've been able to successfully recreate your example code, but at some point in messing around, the script now gets stuck on "Opening a row..." on the tab and doesn't progress.  I've tried executing your example:
https://script.google.com/macros/s/AKfycbzG9_2mWd6x7zFf9V6PH33ORRzZWcVGi_pQs500nbs5Pbdkwy26/exec?id=1P4Lt0kEqzn2BDkK43GxChUebBR0Af3biwcT9ja4aCWg&sheet=Sheet1&row=5&header=1

using a completely separate userid from what I've been using for development, I've checked the Developer's Console to see if I hit some quote (haven't) and have tried creating a completely new project/library and gSheet - all get stuck on the tab.
![screenshot 2017-01-29 at 12 02 04 pm - display 2](https://cloud.githubusercontent.com/assets/3047334/22406593/229c8e3c-e61b-11e6-96dc-589e7656ac3b.png)

Any thoughts would be appreciated - thanks!
- Chris

**Comment by mhawksey** [comment]
So you've modified the code? Hard to say what is wrong without seeing the changed code, are you able to share?

**Comment by cklann1** [comment]
Thanks for the response.  Soon after I posted this, Google serendipity provided a solution with the "Link to cell ranges in Google Sheets" capability - pretty much exactly what I was looking for.
https://gsuiteupdates.googleblog.com/2017/02/link-to-cell-ranges-in-google-sheets.html

Thanks again for all you do for the GAS community!
- Chris
